---

- name: apply raspi-config
  command: raspi-config --apply-os-config

- name: reboot
  shell: "(sleep {{ raspi_config_reboot_delay }} && shutdown -r now) &"
  async: 0
  poll: 0
  notify:
    - wait for reboot

- name: wait for reboot
  local_action: wait_for host={{ inventory_hostname }}
                state=started
                timeout={{ raspi_config_reboot_timeout }} # doesn't appear to work correctly now, instead a simple delay is imposed - that's fine for now
  sudo: false

- name: remove default user
  when: "raspi_config_replace_user['name'] != raspi_config_auth_test_username"
  user: name={{raspi_config_auth_test_username}} state=absent force=yes
  async: 0
  poll: 0
  ignore_errors: True